// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using login.Services.Context;

namespace login.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("login.Models.credentials", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("credential");

                    b.HasData(
                        new
                        {
                            id = 1,
                            password = "Chicag0",
                            userName = "kevincab"
                        },
                        new
                        {
                            id = 2,
                            password = "Chicag0",
                            userName = "kevin"
                        },
                        new
                        {
                            id = 3,
                            password = "Chicag0",
                            userName = "kevycabbb"
                        },
                        new
                        {
                            id = 4,
                            password = "Chicag0",
                            userName = "whatizit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
